pipeline:
  - name: load_data
  - name: filter
    l_freq: 1.0
    h_freq: 30.0
  - name: reference
    type: average
  - name: ica
    n_components: 15
    method: fastica
    find_eog: true
    apply: true
  - name: save_clean_raw
  - name: generate_report
    generate_html: false
